# Generated by Django 3.2.7 on 2021-10-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='products.skus'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='stores.store'),
        ),
    ]
