# Generated by Django 3.2.7 on 2021-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
