# Generated by Django 3.2.7 on 2021-10-08 03:20

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
