# Generated by Django 3.1.12 on 2021-06-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Product id')),
                ('name', models.CharField(max_length=500, verbose_name='Product name')),
                ('department_id', models.CharField(max_length=500, verbose_name='Departament id')),
                ('category_id', models.CharField(max_length=500, verbose_name='Category id')),
                ('brand_id', models.CharField(max_length=500, verbose_name='Brand id')),
                ('link_id', models.CharField(max_length=500, verbose_name='link id')),
                ('ref_id', models.CharField(max_length=500, verbose_name='Reference id')),
                ('is_visible', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('description_short', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('keywords', models.CharField(max_length=100, verbose_name='Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_active', models.BooleanField(default=255, verbose_name='Is active')),
                ('tax_code', models.CharField(max_length=255, verbose_name='Tax code')),
                ('meta_tag_description', models.CharField(max_length=255, verbose_name='Tag description')),
                ('supplier_id', models.CharField(max_length=255, verbose_name='Suplier id')),
                ('show_without_stock', models.BooleanField(default=False, verbose_name='Without stock')),
                ('list_store_id', models.CharField(choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER'), ('NIÑOS', 'NIÑOS'), ('OTROS', 'OTROS')], max_length=255, verbose_name='List store')),
                ('adwords_remrketing_code', models.CharField(max_length=255, null=True)),
                ('lomadee_campaing_code', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoresVtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('app_key', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
