# Generated by Django 3.1.12 on 2021-06-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=15, verbose_name='Colores')),
            ],
            options={
                'verbose_name': 'Colores',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('product_id', models.SlugField(max_length=255, unique=True, verbose_name='Vtex product Id')),
                ('name', models.CharField(max_length=500, verbose_name='Product name')),
                ('sku', models.CharField(max_length=500, unique=True, verbose_name='Product sku')),
                ('link_id', models.CharField(max_length=500, verbose_name='link id')),
                ('reference_id', models.CharField(max_length=500, verbose_name='Reference id')),
                ('is_visible', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('description_short', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('keywords', models.CharField(max_length=100, verbose_name='Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_active', models.BooleanField(default=255, verbose_name='Is active')),
                ('tax_code', models.CharField(max_length=255, verbose_name='Tax code')),
                ('meta_tag_description', models.CharField(max_length=255, verbose_name='Tag description')),
                ('show_without_stock', models.BooleanField(default=False, verbose_name='Without stock')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduts')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=4, verbose_name='Sizes')),
            ],
            options={
                'verbose_name': 'Sizes',
                'verbose_name_plural': 'Sizes',
                'ordering': ['sizes'],
            },
        ),
        migrations.CreateModel(
            name='StoresVtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('app_key', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.colors', verbose_name='Colors')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizes', verbose_name='Sizes')),
            ],
        ),
    ]
