# Generated by Django 3.1.12 on 2021-06-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('category', models.CharField(max_length=50, verbose_name='Department category')),
                ('categories_json', models.JSONField(blank=True, null=True, verbose_name='Complete categories data')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductsApiVtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('product_id', models.SlugField(max_length=255, unique=True, verbose_name='Vtex product Id')),
                ('name', models.CharField(max_length=500, verbose_name='Product name')),
                ('sku', models.CharField(max_length=500, unique=True, verbose_name='Product sku')),
                ('link_id', models.CharField(max_length=500, verbose_name='link id')),
                ('reference_id', models.CharField(max_length=500, verbose_name='Reference id')),
                ('is_visible', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('description_short', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('keywords', models.CharField(max_length=100, verbose_name='Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_active', models.BooleanField(default=255, verbose_name='Is active')),
                ('tax_code', models.CharField(max_length=255, verbose_name='Tax code')),
                ('meta_tag_description', models.CharField(max_length=255, verbose_name='Tag description')),
                ('show_without_stock', models.BooleanField(default=False, verbose_name='Without stock')),
                ('product_data', models.JSONField(blank=True, null=True, verbose_name='Complete product data')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Skus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('sku_id', models.CharField(max_length=50, verbose_name='Sku')),
                ('specification', models.CharField(max_length=50, verbose_name='Specification sku')),
                ('refID', models.PositiveIntegerField(blank=True, default=0)),
                ('is_kit', models.BooleanField(default=False)),
                ('comercial_condition_id', models.PositiveIntegerField(blank=True, default=0)),
                ('sku_json', models.JSONField(blank=True, null=True, verbose_name='Complete sku data')),
            ],
            options={
                'verbose_name': 'Sku',
                'verbose_name_plural': "Sku's",
            },
        ),
        migrations.CreateModel(
            name='StoreDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('department', models.CharField(max_length=50, verbose_name='Store department')),
                ('url_department', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Url')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('department_json', models.JSONField(blank=True, null=True, verbose_name='Complete department data')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.categoriesstore')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AddField(
            model_name='categoriesstore',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productsapivtex'),
        ),
    ]
