# Generated by Django 3.1.12 on 2021-07-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('Id', models.BigIntegerField(blank=True, null=True, verbose_name='ID')),
                ('ArchiveId', models.BigIntegerField(blank=True, null=True, verbose_name='Archive ID')),
                ('SkuId', models.BigIntegerField(blank=True, null=True, verbose_name='Sku ID')),
                ('Name', models.CharField(max_length=500, verbose_name='Name')),
                ('IsMain', models.BooleanField(null=True, verbose_name='Main image')),
                ('Label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label')),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Image url')),
                ('Sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_images', to='products.skus')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_images', to='stores.storesvtex')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': "Image's",
                'ordering': ['SkuId', 'Id'],
            },
        ),
    ]
