# Generated by Django 3.2.7 on 2021-09-23 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skus',
            name='sales_channels',
            field=models.ManyToManyField(related_name='skus', to='stores.SaleChannel', verbose_name="Sales channel's"),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.department'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='price',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.skus'),
        ),
        migrations.AddField(
            model_name='image',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.skus'),
        ),
        migrations.AddField(
            model_name='fixedprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_prices', to='products.price'),
        ),
        migrations.AddField(
            model_name='department',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='stores.store'),
        ),
        migrations.AddField(
            model_name='daterange',
            name='fixed_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_ranges', to='products.fixedprice'),
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.department'),
        ),
        migrations.AddField(
            model_name='brand',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='stores.store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes_type', to='stores.store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.attributetype'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.skus'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('sku', 'attribute_type')},
        ),
    ]
