# Generated by Django 3.1.12 on 2021-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_tag_description',
            field=models.TextField(blank=True, null=True, verbose_name='Tag description'),
        ),
    ]
