# Generated by Django 3.1.12 on 2021-06-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesstore',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='storedepartment',
            old_name='department',
            new_name='department_name',
        ),
        migrations.AddField(
            model_name='categoriesstore',
            name='category_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='storedepartment',
            name='department_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
