# Generated by Django 3.1.12 on 2021-07-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='price',
            name='store',
        ),
        migrations.DeleteModel(
            name='FixedPrices',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
