# Generated by Django 3.1.12 on 2021-06-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesstore',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productsapivtex',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='skus',
            options={'verbose_name': 'Sku', 'verbose_name_plural': "Sku's"},
        ),
        migrations.AlterModelOptions(
            name='sotredepartment',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='sotredepartment',
            name='url_department',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Url'),
        ),
    ]
