# Generated by Django 3.1.12 on 2021-07-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210630_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsapivtex',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='productsapivtex',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productsapivtex',
            name='tax_code',
        ),
        migrations.AddField(
            model_name='productsapivtex',
            name='skus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_sku', to='products.skus'),
        ),
        migrations.AddField(
            model_name='skus',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skus',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sku'),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='description_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='link_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='link id'),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='meta_tag_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag description'),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
