# Generated by Django 3.1.12 on 2021-08-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.department'),
        ),
    ]
