# Generated by Django 4.2.5 on 2023-09-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributetype'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.skus'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='daterange',
            name='fixed_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.fixedprice'),
        ),
        migrations.AlterField(
            model_name='fixedprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.price'),
        ),
        migrations.AlterField(
            model_name='image',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.skus'),
        ),
        migrations.AlterField(
            model_name='price',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.skus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.department'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='sales_channels',
            field=models.ManyToManyField(to='stores.salechannel', verbose_name="Sales channel's"),
        ),
    ]
