# Generated by Django 3.1.12 on 2021-07-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210729_0559'),
        ('products', '0002_image'),
    ]

    operations = [
    ]
