# Generated by Django 3.1.12 on 2021-08-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcateogry',
            new_name='sub_category',
        ),
    ]
