# Generated by Django 3.1.12 on 2021-07-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_storesvtex_departments'),
        ('products', '0003_auto_20210709_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesstore',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productsapivtex',
            name='skus',
        ),
        migrations.RemoveField(
            model_name='storedepartment',
            name='categories',
        ),
        migrations.AddField(
            model_name='categoriesstore',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.storedepartment'),
        ),
        migrations.AddField(
            model_name='productsapivtex',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.categoriesstore'),
        ),
        migrations.AddField(
            model_name='skus',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_sku', to='products.productsapivtex'),
        ),
        migrations.AddField(
            model_name='storedepartment',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_store', to='stores.storesvtex'),
        ),
    ]
