# Generated by Django 3.1.12 on 2021-07-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210709_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='sku_id',
            field=models.CharField(max_length=50, verbose_name='Sku ID'),
        ),
    ]
