# Generated by Django 3.1.12 on 2021-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_fixedprices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsapivtex',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='productsapivtex',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department name'),
        ),
    ]
