# Generated by Django 3.1.12 on 2021-08-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_attribute_attributetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='skus',
            name='total_quantity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quantity sku'),
        ),
    ]
