# Generated by Django 3.1.12 on 2021-07-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210719_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsapivtex',
            name='description_short',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='meta_tag_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tag description'),
        ),
    ]
