# Generated by Django 3.1.12 on 2021-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210719_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsapivtex',
            name='product_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='Vtex product Id'),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title'),
        ),
    ]
