# Generated by Django 3.1.12 on 2021-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210719_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='comercial_condition_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skus',
            name='refID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
