# Generated by Django 3.1.12 on 2021-07-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210720_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='product_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='sku_id',
            field=models.CharField(max_length=10, verbose_name='Sku ID'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='specification',
            field=models.CharField(max_length=255, verbose_name='Specification sku'),
        ),
    ]
