# Generated by Django 3.1.12 on 2021-07-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210720_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsapivtex',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Product name'),
        ),
    ]
