# Generated by Django 3.1.12 on 2021-07-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210721_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsapivtex',
            name='product_id',
            field=models.CharField(max_length=30, verbose_name='Vtex product Id'),
        ),
    ]
