# Generated by Django 3.1.12 on 2021-07-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210721_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesstore',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storedepartment',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storedepartment',
            name='tag_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='storedepartment',
            name='department_id',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Department id'),
        ),
        migrations.AlterField(
            model_name='storedepartment',
            name='department_name',
            field=models.CharField(max_length=50, verbose_name='Department name'),
        ),
        migrations.AlterField(
            model_name='storedepartment',
            name='url_department',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Url department'),
        ),
    ]
