# Generated by Django 3.1.12 on 2021-07-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_storesvtex_departments'),
        ('products', '0012_auto_20210726_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('listPrice', models.BigIntegerField(blank=True, null=True, verbose_name='List price')),
                ('costPrice', models.BigIntegerField(blank=True, null=True, verbose_name='Cost price')),
                ('markup', models.BigIntegerField(blank=True, null=True, verbose_name='Mark up')),
                ('basePrice', models.BigIntegerField(blank=True, null=True, verbose_name='Base price')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.skus')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storesvtex')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': "Price's",
            },
        ),
        migrations.CreateModel(
            name='FixedPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('tradePolicyId', models.CharField(max_length=50, verbose_name='Trade porlice ID')),
                ('value', models.BigIntegerField(blank=True, null=True, verbose_name='Value')),
                ('listPrice', models.BigIntegerField(blank=True, null=True, verbose_name='List price')),
                ('minQuantity', models.IntegerField(blank=True, null=True, verbose_name='Minimun quantity')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixedPrices', to='products.price')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storesvtex')),
            ],
            options={
                'verbose_name': 'FixedPrice',
                'verbose_name_plural': "Fixed price's",
            },
        ),
    ]
