# Generated by Django 3.1.12 on 2021-07-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_fixedprices_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsapivtex',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='productsapivtex',
            name='brand_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand id'),
        ),
        migrations.AddField(
            model_name='productsapivtex',
            name='category_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category id'),
        ),
        migrations.AddField(
            model_name='productsapivtex',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Department id'),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='product_id',
            field=models.CharField(max_length=50, verbose_name='Vtex product Id'),
        ),
        migrations.AlterField(
            model_name='productsapivtex',
            name='reference_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reference id'),
        ),
    ]
