# Generated by Django 3.1.12 on 2021-07-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210727_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skus',
            name='specification',
        ),
        migrations.AddField(
            model_name='skus',
            name='activate_if_possible',
            field=models.BooleanField(default=False, verbose_name='Possible activation of sku'),
        ),
        migrations.AddField(
            model_name='skus',
            name='kit_items_sell_apart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skus',
            name='packaged_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skus',
            name='packaged_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skus',
            name='packaged_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Packaged weight Kg'),
        ),
        migrations.AddField(
            model_name='skus',
            name='packaged_width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skus',
            name='sku_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name sku'),
        ),
        migrations.AddField(
            model_name='skus',
            name='unit_multiplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skus',
            name='comercial_condition_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skus',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active sku'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='is_kit',
            field=models.BooleanField(default=False, verbose_name='sku is kit'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='refID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference id'),
        ),
    ]
