# Generated by Django 3.1.12 on 2021-07-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210727_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skus',
            old_name='kit_items_sell_apart',
            new_name='is_inventoried',
        ),
        migrations.RenameField(
            model_name='skus',
            old_name='unit_multiplier',
            new_name='manufacter_code',
        ),
        migrations.RenameField(
            model_name='skus',
            old_name='refID',
            new_name='ref_id',
        ),
        migrations.RemoveField(
            model_name='skus',
            name='activate_if_possible',
        ),
        migrations.AddField(
            model_name='skus',
            name='is_transported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skus',
            name='reference_stock_id',
            field=models.BooleanField(default=False),
        ),
    ]
