# Generated by Django 3.1.12 on 2021-07-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210728_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='reference_stock_id',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
