# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='products.proto',
  package='products',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eproducts.proto\x12\x08products\x1a\x1bgoogle/protobuf/empty.proto\"\xa2\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x65xternal_id\x18\x02 \x01(\x05\x12\r\n\x05\x62rand\x18\x03 \x01(\x05\x12\x12\n\ndepartment\x18\x04 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\x05\x12\x14\n\x0csub_category\x18\x06 \x01(\x05\x12\r\n\x05title\x18\x07 \x01(\t\x12\x1c\n\x14meta_tag_description\x18\x08 \x01(\t\"\x14\n\x12ProductListRequest\"$\n\x16ProductRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xaf\x02\n\x11ProductController\x12;\n\x04List\x12\x1c.products.ProductListRequest\x1a\x11.products.Product\"\x00\x30\x01\x12\x30\n\x06\x43reate\x12\x11.products.Product\x1a\x11.products.Product\"\x00\x12\x41\n\x08Retrieve\x12 .products.ProductRetrieveRequest\x1a\x11.products.Product\"\x00\x12\x30\n\x06Update\x12\x11.products.Product\x1a\x11.products.Product\"\x00\x12\x36\n\x07\x44\x65stroy\x12\x11.products.Product\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='products.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='products.Product.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='external_id', full_name='products.Product.external_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brand', full_name='products.Product.brand', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='department', full_name='products.Product.department', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='products.Product.category', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sub_category', full_name='products.Product.sub_category', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='products.Product.title', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta_tag_description', full_name='products.Product.meta_tag_description', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=220,
)


_PRODUCTLISTREQUEST = _descriptor.Descriptor(
  name='ProductListRequest',
  full_name='products.ProductListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=242,
)


_PRODUCTRETRIEVEREQUEST = _descriptor.Descriptor(
  name='ProductRetrieveRequest',
  full_name='products.ProductRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='products.ProductRetrieveRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=280,
)

DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['ProductListRequest'] = _PRODUCTLISTREQUEST
DESCRIPTOR.message_types_by_name['ProductRetrieveRequest'] = _PRODUCTRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.Product)
  })
_sym_db.RegisterMessage(Product)

ProductListRequest = _reflection.GeneratedProtocolMessageType('ProductListRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTLISTREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.ProductListRequest)
  })
_sym_db.RegisterMessage(ProductListRequest)

ProductRetrieveRequest = _reflection.GeneratedProtocolMessageType('ProductRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTRETRIEVEREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.ProductRetrieveRequest)
  })
_sym_db.RegisterMessage(ProductRetrieveRequest)



_PRODUCTCONTROLLER = _descriptor.ServiceDescriptor(
  name='ProductController',
  full_name='products.ProductController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=283,
  serialized_end=586,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='products.ProductController.List',
    index=0,
    containing_service=None,
    input_type=_PRODUCTLISTREQUEST,
    output_type=_PRODUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='products.ProductController.Create',
    index=1,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=_PRODUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='products.ProductController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_PRODUCTRETRIEVEREQUEST,
    output_type=_PRODUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='products.ProductController.Update',
    index=3,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=_PRODUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='products.ProductController.Destroy',
    index=4,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTCONTROLLER)

DESCRIPTOR.services_by_name['ProductController'] = _PRODUCTCONTROLLER

# @@protoc_insertion_point(module_scope)
