# Generated by Django 3.1.12 on 2021-08-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_skus_total_quantity'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='products.skus'),
        ),
    ]
