# Generated by Django 3.1.12 on 2021-09-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=255)),
                ('slug_name', models.SlugField(blank=True, null=True, unique=True)),
                ('url_enviroment', models.CharField(blank=True, max_length=500, null=True)),
                ('api_key', models.CharField(max_length=500)),
                ('api_token', models.CharField(max_length=500)),
                ('sync_status', models.BooleanField(default=False, verbose_name='Task begun Finish')),
                ('status', models.BooleanField(default=False, verbose_name='Valid connection')),
                ('store_type', models.CharField(max_length=500, verbose_name='Type of store')),
                ('last_page', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Last page get of skus')),
                ('disable_filters', models.BooleanField(default=False, verbose_name='Disable filters')),
                ('apply_filter_enable_products', models.BooleanField(default=True, verbose_name='Enable products')),
                ('apply_filter_enable_skus', models.BooleanField(default=True, verbose_name='Enable skus')),
                ('apply_filter_price', models.BooleanField(default=True, verbose_name='Valid price')),
                ('apply_filter_image', models.BooleanField(default=True, verbose_name='Valid image')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
