# Generated by Django 3.2.7 on 2021-09-23 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('seller_id', models.CharField(help_text='coud be a text instade a number', max_length=500, verbose_name='Id of seller')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name of seller')),
                ('slug_name', models.SlugField(blank=True, null=True)),
                ('hibrit_payment_options', models.BooleanField(default=False, null=True, verbose_name='Various forms of payment')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('description', models.CharField(max_length=500, verbose_name='Description of seller')),
                ('raw_json', models.JSONField(verbose_name='Raw data')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'default_related_name': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('store_type', models.CharField(max_length=500, verbose_name='Type of store')),
                ('name', models.CharField(max_length=255, verbose_name='Name of store')),
                ('slug_name', models.SlugField(blank=True, null=True)),
                ('url_enviroment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Url enviroment')),
                ('sync_status', models.BooleanField(default=False, verbose_name='Task begun Finish')),
                ('creating_updating_elements_status', models.BooleanField(default=False, verbose_name='Task principal store elments')),
                ('domain', models.CharField(blank=True, max_length=500, null=True, verbose_name='Domain of store')),
                ('status', models.BooleanField(default=False, verbose_name='Valid connection')),
                ('api_key', models.CharField(max_length=500)),
                ('api_token', models.CharField(max_length=500)),
                ('disable_filters', models.BooleanField(default=False, verbose_name='Disable filters')),
                ('apply_filter_enable_products', models.BooleanField(default=True, verbose_name='Enable products')),
                ('apply_filter_enable_skus', models.BooleanField(default=True, verbose_name='Enable skus')),
                ('apply_filter_price', models.BooleanField(default=True, verbose_name='Valid price')),
                ('apply_filter_image', models.BooleanField(default=True, verbose_name='Valid image')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='SkuSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('is_active', models.BooleanField(verbose_name='Status')),
                ('raw_json', models.JSONField(verbose_name='Raw data')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_seller', to='stores.seller', verbose_name='Seller')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_seller', to='products.skus', verbose_name='Sku')),
            ],
            options={
                'verbose_name': 'Sku Seller',
                'verbose_name_plural': 'Skus Sellers',
                'default_related_name': 'sku_seller',
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='stores.store', verbose_name='Store'),
        ),
        migrations.CreateModel(
            name='SaleChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('external_id', models.BigIntegerField(verbose_name='External ID')),
                ('slug_name', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('sellers', models.ManyToManyField(related_name='sales_channel', to='stores.Seller', verbose_name='Sellers')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_channel', to='stores.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Sale Channel',
                'verbose_name_plural': 'Sales Channel',
                'default_related_name': 'sales_channel',
            },
        ),
    ]
