# Generated by Django 3.1.12 on 2021-06-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storesvtex',
            old_name='app_key',
            new_name='api_token',
        ),
        migrations.RenameField(
            model_name='storesvtex',
            old_name='token',
            new_name='appi_key',
        ),
        migrations.RenameField(
            model_name='storesvtex',
            old_name='url',
            new_name='url_enviroment',
        ),
    ]
