# Generated by Django 3.1.12 on 2021-08-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='apply_filters',
            field=models.BooleanField(default=True, verbose_name='Apply filters'),
        ),
    ]
