# Generated by Django 4.2.5 on 2023-09-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_attribute_attribute_type_alter_attribute_sku_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salechannel',
            name='sellers',
            field=models.ManyToManyField(to='stores.seller', verbose_name='Sellers'),
        ),
        migrations.AlterField(
            model_name='salechannel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='skuseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.seller', verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='skuseller',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.skus', verbose_name='Sku'),
        ),
    ]
