# Generated by Django 3.2.9 on 2021-12-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skus',
            name='sku_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='total_quantity',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Quantity sku'),
        ),
    ]
