# Generated by Django 3.2.11 on 2022-01-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(fields=('external_id', 'product'), name='unique_sku'),
        ),
    ]
