# Generated by Django 3.2.9 on 2021-12-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20211130_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='sku_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
