# Generated by Django 3.1.12 on 2021-07-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210630_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesvtex',
            name='url_enviroment',
            field=models.CharField(max_length=500),
        ),
    ]
