# Generated by Django 3.2.9 on 2021-12-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_skus_sku_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='skus',
            name='stores_skus_is_acti_37bd3d_idx',
        ),
        migrations.AddIndex(
            model_name='skus',
            index=models.Index(fields=['is_active', 'external_id', 'total_quantity', 'sku_price', 'search_vector'], name='stores_skus_is_acti_470aaa_idx'),
        ),
    ]
