# Generated by Django 3.2.9 on 2021-12-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_skus_sku_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daterange',
            options={'verbose_name': 'Date range', 'verbose_name_plural': "Date range's"},
        ),
        migrations.AlterModelOptions(
            name='fixedprice',
            options={'default_related_name': 'fixed_prices', 'verbose_name': 'Fixed price', 'verbose_name_plural': "Fixed price's"},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'default_related_name': 'price', 'verbose_name': 'Price', 'verbose_name_plural': "Price's"},
        ),
        migrations.RemoveField(
            model_name='daterange',
            name='fixed_price',
        ),
        migrations.AddField(
            model_name='fixedprice',
            name='date_range',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_prices', to='stores.daterange', verbose_name='Date range'),
        ),
        migrations.AlterField(
            model_name='price',
            name='base_price',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='sku',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='stores.skus', verbose_name='Sku'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='total_quantity',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Quantity sku'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('attribute_type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together={('name', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_id', 'store', 'name', 'image_url')},
        ),
    ]
