# Generated by Django 3.1.12 on 2021-07-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210709_1632'),
        ('stores', '0003_auto_20210707_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesvtex',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_store', to='products.categoriesstore'),
        ),
        migrations.AddField(
            model_name='storesvtex',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_store', to='products.storedepartment'),
        ),
    ]
