# Generated by Django 3.2.10 on 2021-12-16 21:02

import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_skus_sku_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40)),
                ('function_name', models.CharField(max_length=50)),
                ('primary_key', models.PositiveIntegerField()),
                ('all_data', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Update Model',
                'verbose_name_plural': 'Update Models',
                'default_related_name': 'update_models',
            },
        ),
        migrations.AlterModelOptions(
            name='daterange',
            options={'verbose_name': 'Date range', 'verbose_name_plural': "Date range's"},
        ),
        migrations.AlterModelOptions(
            name='fixedprice',
            options={'default_related_name': 'fixed_prices', 'verbose_name': 'Fixed price', 'verbose_name_plural': "Fixed price's"},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'default_related_name': 'price', 'verbose_name': 'Price', 'verbose_name_plural': "Price's"},
        ),
        migrations.RemoveField(
            model_name='daterange',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='daterange',
            name='serializer_data',
        ),
        migrations.RemoveField(
            model_name='fixedprice',
            name='serializer_data',
        ),
        migrations.RemoveField(
            model_name='price',
            name='serializer_data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serializer_data',
        ),
        migrations.RemoveField(
            model_name='salechannel',
            name='serializer_data',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='serializer_data',
        ),
        migrations.RemoveField(
            model_name='skuseller',
            name='serializer_data',
        ),
        migrations.AddField(
            model_name='attribute',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='brand',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='category',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='daterange',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='department',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='fixedprice',
            name='date_rage_data',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fixedprice',
            name='date_range',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_price', to='stores.daterange', verbose_name='Date range'),
        ),
        migrations.AddField(
            model_name='fixedprice',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='image',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='price',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='price',
            name='fixed_prices_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), default=list, editable=False, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='salechannel',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='skuseller',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='store',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='typestore',
            name='first_time',
            field=models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='slug_name',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='base_price',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Base price'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('attribute_type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together={('name', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_id', 'store', 'name', 'image_url')},
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('first_time', models.BooleanField(default=True, editable=False, help_text='Was saved in database before.', verbose_name='First time')),
                ('raw_json', models.JSONField(blank=True, null=True, verbose_name='Raw data')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('external_id', models.BigIntegerField(blank=True, null=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Active sku')),
                ('is_inventoried', models.BooleanField(blank=True, default=False, null=True)),
                ('total_quantity', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Quantity sku')),
                ('search', models.TextField(blank=True, null=True, verbose_name='Search')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Search vector')),
                ('is_transported', models.BooleanField(blank=True, default=False, null=True)),
                ('is_kit', models.BooleanField(blank=True, default=False, null=True, verbose_name='sku is kit')),
                ('comercial_condition_id', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacter_code', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference id')),
                ('packaged_height', models.CharField(blank=True, max_length=50, null=True)),
                ('packaged_length', models.CharField(blank=True, max_length=50, null=True)),
                ('packaged_width', models.CharField(blank=True, max_length=50, null=True)),
                ('packaged_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Packaged weight Kg')),
                ('reference_stock_id', models.BooleanField(blank=True, default=False, null=True)),
                ('sellers_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, editable=False, size=None)),
                ('images_url', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, editable=False, size=None)),
                ('sku_price', models.FloatField(blank=True, editable=False, null=True, verbose_name='Price')),
                ('attributes_data', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), default=list, editable=False, size=None)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='stores.product')),
                ('sales_channels', models.ManyToManyField(related_name='skus', to='stores.SaleChannel', verbose_name="Sales channel's")),
            ],
            options={
                'verbose_name': 'Sku',
                'verbose_name_plural': "Sku's",
                'default_related_name': 'skus',
            },
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='serializer_data',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='skus',
            field=models.ManyToManyField(related_name='attributes', to='stores.Sku', verbose_name='Skus'),
        ),
        migrations.AlterField(
            model_name='image',
            name='skus',
            field=models.ManyToManyField(related_name='images', to='stores.Sku', verbose_name='Skus'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='stores.sku'),
        ),
        migrations.AlterField(
            model_name='price',
            name='sku',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='stores.sku', verbose_name='Sku'),
        ),
        migrations.AlterField(
            model_name='skuseller',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_seller', to='stores.sku', verbose_name='Sku'),
        ),
        migrations.DeleteModel(
            name='Skus',
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['is_active', 'external_id'], name='stores_sku_is_acti_f7f375_idx'),
        ),
    ]
