# Generated by Django 3.1.12 on 2021-07-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20210709_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesvtex',
            name='categories',
        ),
    ]
