# Generated by Django 3.2.9 on 2021-12-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20211202_1900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('attribute_type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together={('name', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_id', 'store')},
        ),
    ]
