# Generated by Django 3.2.11 on 2022-01-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20220120_0112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(fields=('attribute_type', 'value'), name='unique_attribute'),
        ),
        migrations.AddConstraint(
            model_name='attributetype',
            constraint=models.UniqueConstraint(fields=('name', 'store'), name='unique_attribute_type'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('image_id', 'store', 'name', 'image_url'), name='unique_image'),
        ),
    ]
