# Generated by Django 3.2.11 on 2022-01-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20220120_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='total_quantity',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Quantity sku'),
        ),
    ]
