# Generated by Django 3.2.9 on 2021-12-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20211205_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='total_quantity',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Quantity sku'),
        ),
    ]
