# Generated by Django 3.1.12 on 2021-07-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_storesvtex_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesvtex',
            name='departments',
        ),
    ]
