# Generated by Django 3.2.11 on 2022-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_sku_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='total_quantity',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Quantity sku'),
        ),
    ]
