# Generated by Django 3.2.7 on 2021-10-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('engine_displacement', models.FloatField(blank=True, null=True, verbose_name='Engine displacement')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='Capacity')),
                ('capacity_unit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Capacity unit')),
                ('capacity_unit_desc', models.TextField(blank=True, null=True, verbose_name='Capacity unit description')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('reference_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Reference id')),
                ('series_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Series id')),
                ('chassis', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chassis')),
                ('engine', models.CharField(blank=True, max_length=500, null=True, verbose_name='Engine')),
                ('model_year', models.IntegerField(verbose_name='Model year')),
                ('manifest', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manifest')),
                ('article_nit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Article nit')),
                ('kilometraje', models.FloatField(blank=True, null=True, verbose_name='kilometraje')),
                ('license_plate', models.CharField(blank=True, max_length=500, null=True, verbose_name='License plate')),
                ('city_license_plate', models.CharField(blank=True, max_length=500, null=True, verbose_name="City car's license plate")),
                ('warranty_expiration', models.DateField(blank=True, null=True, verbose_name='Warrranty expiration')),
                ('customer_nit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer nit')),
                ('sales_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sales type')),
                ('sales_type_desc', models.TextField(blank=True, null=True, verbose_name='Sales type description')),
                ('sales_plans', models.FloatField(blank=True, null=True, verbose_name='Sales Plans')),
                ('sales_plan_desc', models.TextField(blank=True, null=True, verbose_name='Sales plan description')),
                ('date_sale', models.DateField(blank=True, null=True, verbose_name='Date sale')),
                ('fecha_obligatorio', models.DateField(blank=True, null=True, verbose_name='Fecha obligatorio')),
                ('technical_mechanical_date', models.DateField(blank=True, null=True, verbose_name='Tecnical-mechanical date')),
                ('insurance_nit', models.CharField(blank=True, max_length=500, null=True, verbose_name='insurance nit')),
                ('user_nit', models.CharField(blank=True, max_length=500, null=True, verbose_name='User nit')),
                ('doors', models.FloatField(blank=True, null=True, verbose_name='Car doors')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year')),
                ('model', models.CharField(max_length=500, verbose_name='Model')),
                ('model_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Model id')),
                ('brand', models.CharField(max_length=500, verbose_name='Brand')),
                ('model_desc', models.TextField(blank=True, null=True, verbose_name='Model description')),
                ('brand_desc', models.TextField(blank=True, null=True, verbose_name='Brand description')),
                ('color', models.CharField(blank=True, max_length=500, null=True, verbose_name='color')),
                ('color_desc', models.TextField(blank=True, null=True, verbose_name='Color description')),
                ('unit_value', models.FloatField(blank=True, null=True, verbose_name='Unit value')),
                ('fuel', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuel')),
                ('fuel_description', models.TextField(blank=True, null=True, verbose_name='Fuel description')),
                ('date_last_entry', models.DateTimeField(blank=True, null=True, verbose_name='Date last entry')),
                ('usado_comprado', models.FloatField(blank=True, null=True, verbose_name='Usado comprado')),
                ('usado_retomado', models.FloatField(blank=True, null=True, verbose_name='Usado retomado')),
                ('es_flota', models.BooleanField(blank=True, null=True, verbose_name='Es flota')),
                ('transaction_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Transaction id')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
