# Generated by Django 3.2.7 on 2021-09-22 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='ModelYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.model', verbose_name='')),
            ],
            options={
                'verbose_name': 'ModelYear',
                'verbose_name_plural': 'ModelYears',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_nit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Buyer nit')),
                ('sales_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sales type')),
                ('sales_type_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Des sales type ')),
                ('sales_plan', models.FloatField(blank=True, null=True, verbose_name='Sales Plan')),
                ('sales_plan_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Des Tipo Venta')),
                ('date_sale', models.DateField(verbose_name='Date Field')),
                ('fecha_obligatorio', models.DateField(blank=True, null=True, verbose_name='Fecha obligatorio')),
                ('user_nit', models.CharField(blank=True, max_length=500, null=True, verbose_name='User nit')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand', verbose_name='Brand')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.model', verbose_name='Model')),
                ('model_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.modelyear', verbose_name='Model year')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='SkuVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('es_flota', models.BooleanField(blank=True, null=True, verbose_name='Es flota')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('reference_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Reference id')),
                ('series_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Series id')),
                ('manifest', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manifest')),
                ('article_nit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nit article')),
                ('license_plate', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nit')),
                ('city_license_plate', models.CharField(blank=True, max_length=500, null=True, verbose_name="City car's license plate")),
                ('warranty_expiration', models.DateField(blank=True, null=True, verbose_name='Warrranty expiration')),
                ('technical_mechanical_date', models.DateField(blank=True, null=True, verbose_name='Tecnical-mechanical date')),
                ('insurance_nit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Insurance nit')),
                ('color', models.CharField(blank=True, max_length=500, null=True, verbose_name='Color')),
                ('color_description', models.TextField(blank=True, null=True, verbose_name='Color description')),
                ('engine_displacement', models.FloatField(blank=True, null=True, verbose_name='Engine displacement')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='Capacity')),
                ('capacity_unit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Engine displacement')),
                ('capacity_unit_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Capatity unit description')),
                ('chassis', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chassis')),
                ('engine', models.CharField(blank=True, max_length=500, null=True, verbose_name='Engine')),
                ('kilometraje', models.FloatField(blank=True, null=True, verbose_name='kilometraje')),
                ('doors', models.FloatField(blank=True, null=True, verbose_name='Car doors')),
                ('fuel', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuel')),
                ('fuel_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuel description')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('sku_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
